<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="turretbot" params="parent prefix *origin">

  <xacro:property name="base_x" value="0.10" />
  <xacro:property name="base_y" value="0.10" />
  <xacro:property name="base_z" value="0.15" />

  <xacro:property name="platform_x" value="0.10" />
  <xacro:property name="platform_y" value="0.10" />
  <xacro:property name="platform_z" value="0.05" />\

    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}base_link" />
    </joint>

    <!-- Base Link -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${base_z / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x} ${base_y} ${base_z}"/>
        </geometry>
      </visual>
    
      <collision>
        <origin xyz="0 0 ${base_z / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x} ${base_y} ${base_z}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}base_to_platform_joint" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}platform_link" />
      <origin xyz="0 0 ${base_z + 0.005}" rpy="0 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <!-- Platform Link -->
    <link name="${prefix}platform_link">
      <visual>
        <origin xyz="0 0 ${platform_z / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${platform_x} ${platform_y} ${platform_z}"/>
        </geometry>
      </visual>
    
      <collision>
        <origin xyz="0 0 ${platform_z / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${platform_x} ${platform_y} ${platform_z}"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>
</robot> 
